### ISSUE TITLE
Unexpected crash on dashboard of user

### ISSUE THREAD

**Issue by Rekkonnect** [0x5bfa/FluentHub#493] opened 2024-07-22 09:18 UTC
### 🪟 What version of Windows is this issue present?

🪟 Windows 10

### 🔢 What version of FluentHub are you on?

0.8.60.0 | x64 | RELEASE

### 📄 Description

After logging in, as the home page was loading my repositories and data, it suddenly failed saying that something went wrong. This happens every time I retry on this account. The log mentions a potential bug in Octokit (see stack trace below).

### 📑 Stack Trace

<details><summary>Stack trace details</summary><div>

```
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1528
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 183
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1528
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 183
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1528
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 183
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1528
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 183
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1528
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 183
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in /_/Octokit/SimpleJson.cs:line 596
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in /_/Octokit/Http/JsonHttpPipeline.cs:line 62
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 696
   at Octokit.ApiConnection.GetPage[TU](Uri uri, IDictionary`2 parameters, String accepts, ApiOptions options, Func`2 preprocessResponseBody) in /_/Octokit/Http/ApiConnection.cs:line 672
   at Octokit.ApiConnection.<>c__DisplayClass19_0`1.<<GetAll>b__0>d.MoveNext() in /_/Octokit/Http/ApiConnection.cs:line 230
--- End of stack trace from previous location ---
   at Octokit.ApiPagination.GetAllPages[T](Func`1 getFirstPage, Uri uri) in /_/Octokit/Clients/ApiPagination.cs:line 23
   at FluentHub.Octokit.Queries.Users.ActivityQueries.GetAllAsync(String login)
   at FluentHub.App.ViewModels.Viewers.DashBoardViewModel.LoadHomeContentsAsync()
   at FluentHub.App.ViewModels.Viewers.DashBoardViewModel.LoadUserHomePageAsync()
```

</div></details>

**Comment by 0x5bfa** [comment] 2024-07-22 10:34
Thank for the report!
Octokit has fixed this issue in the latest release v13 accompanying partial fix from v12. However, we haven't published the package of updated version to the Store yet. We hopefully wanna do it in this summer.

duplicate of #470

**Closed** 2024-07-22 10:34 UTC

**Comment by 0x5bfa** [comment] 2024-07-22 15:01
@Lamparter its not planned but closed as duplication

**Comment by Lamparter** [comment] 2024-07-22 15:29
> @Lamparter its not planned but closed as duplication

I know

**Comment by Lamparter** [comment] 2024-07-22 15:30
Closing something as not planned also means 'wontfix/can't replicate/stale/duplicate'
It's in GitHub developer guide
